#import '@/modules/auth/graphql/UserFragment.gql'
#import '@/modules/dashboard/modules/finances/graphql/AccountFragment.gql'
#import '@/modules/dashboard/modules/finances/graphql/CategoryFragment.gql'

fragment RecordFragment on Record {
  id
  type
  amount
  date
  description
  note
  tags
  account {
    ...AccountFragment
  }
  category {
    ...CategoryFragment
  }
  user {
    ...UserFragment
  }
}
